#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
#@ def config():
#@  return {
#@    "auths": {
#@      data.values.tap.credentials.tanzuNet.host: {
#@        "username": data.values.tap.credentials.tanzuNet.username,
#@        "password": data.values.tap.credentials.tanzuNet.password
#@      }
#@    }
#@  }
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-registry
  namespace: #@ data.values.tap.namespace
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: #@ json.encode(config())
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-registry
  namespace: #@ data.values.tap.namespace
spec:
  toNamespaces:
  - '*'
---
apiVersion: v1
kind: Secret
metadata:
  name: build-service-custom-ca
  namespace: #@ data.values.tap.namespace
type: service.binding/ca-certificates
stringData:
  type: ca-certificates
  provider: sample
  custom_ca.pem: #@ data.values.tap.domains.ca_cert_data
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: build-service-custom-ca
  namespace: #@ data.values.tap.namespace
spec:
  toNamespaces:
  - '*'
