apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-install-gitops
  namespace: tap-install-gitops
  annotations:
    kapp.k14s.io/change-group: tap-install-gitops/app
    kapp.k14s.io/change-rule: "upsert after upserting tap-install-gitops/rbac"
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: https://github.com/gorkemozlu/tap-install-gitops.git
      ref: origin/multi-cluster
      secretRef:
        name: tap-install-gitops-github
  template:
  - ytt:
      paths:
      - config
      - config-full
#      - additional/external-dns
      valuesFrom:
      - configMapRef:
          name: tap-install-gitops
      - secretRef:
          name: tap-install-gitops
  deploy:
  - kapp: {}
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: full-tbs-deps
  namespace: tap-install-gitops
  annotations:
    kapp.k14s.io/change-group: tbs
    kapp.k14s.io/change-rule: "upsert after upserting tap-install-gitops/app"
    kapp.k14s.io/change-rule.repo: "upsert after upserting tap-install/tbs-repo"
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  packageRef:
    refName: full-tbs-deps.tanzu.vmware.com
    versionSelection:
      constraints: #@ str(data.values.tap.tbs.version)
      prereleases: {}
  serviceAccountName: tap-install-gitops-sa